# Gitleaks configuration for secret detection
title = "Security Scanner Configuration"

[extend]
useDefault = true

[[rules]]
description = "Hardcoded tokens in properties files"
id = "property-token"
regex = '''(?i)(token|password|secret|key|api[_-]?key)\s*[=:]\s*['"]*([a-zA-Z0-9\-_]{8,})['"]*'''
path = '''.*\.(properties|yml|yaml|env)$'''

[[rules]]
description = "Base64 encoded tokens"
id = "base64-token"
regex = '''[a-zA-Z0-9+/]{20,}={0,2}'''
path = '''.*\.(properties|yml|yaml|java)$'''

[[rules]]
description = "JWT tokens"
id = "jwt-token"
regex = '''eyJ[a-zA-Z0-9_/+\-=]+\.eyJ[a-zA-Z0-9_/+\-=]+\.[a-zA-Z0-9_/+\-=]+'''

[[rules]]
description = "Generic secrets in Java files"
id = "java-secrets"
regex = '''(?i)(secret|token|password|key)\s*=\s*['"]+([a-zA-Z0-9\-_]{8,})['"]+'''
path = '''.*\.java$'''

[allowlist]
description = "Allow test tokens"
regexes = [
    '''test-token-\w+''',
    '''TEST_TOKEN''',
    '''example-token'''
]

paths = [
    '''.*test.*''',
    '''.*Test.*'''
] 