name: Hello World Pipeline

on:
  push:
    branches: [ devops/github-action-pipeline ]
  pull_request:
    branches: [ devops/github-action-pipeline ]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World"
